from enum import Enum

class FrontendState(Enum):
    """Enum representing various states of the frontend."""
    UNAUTHORIZED = "UNAUTHORIZED"
    BOOKING_PREVIEW = "BOOKING_PREVIEW"
    BOOKING_PREVIEW_ERROR = "BOOKING_PREVIEW_ERROR"
    BOOKING_COMPLETED = "BOOKING_COMPLETED"
    BOOKING_COMPLETED_ERROR = "BOOKING_COMPLETED_ERROR"
    ADDED_TO_CALENDAR = "ADDED_TO_CALENDAR"
    CALENDAR_ERROR = "CALENDAR_ERROR" 
    NO_STATE = "NO_STATE"
    PROCCESING_UPGRADE = "PROCCESING_UPGRADE"

class FlowState(Enum):
    """Enum representing various states of the flow."""
    INITIAL_STATE = "INITIAL_STATE"
    FETCHED_HOTELS = "FETCHED_HOTELS"
    FETCHED_HOTEL = "FETCHED_HOTEL"
    FETCHED_ROOM = "FETCHED_ROOM"
    BOOKING_PREVIEW_INITIATED = "BOOKING_PREVIEW_INITIATED"
    BOOKING_PREVIEW_COMPLETED = "BOOKING_PREVIEW_COMPLETED"
    BOOKING_INITIATED = "BOOKING_INITIATED"
    BOOKING_COMPLETED = "BOOKING_COMPLETED"
    FETCHED_BOOKINGS = "FETCHED_BOOKINGS"
    ADDED_TO_CALENDAR = "ADDED_TO_CALENDAR"
    BOOKING_AUTORIZED = "BOOKING_AUTORIZED"
    CALENDAR_AUTORIZED = "CALENDAR_AUTORIZED"
    PROCCESING_UPGRADE = "PROCCESING_UPGRADE"

